version: '3'
services:
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  web:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - redis
    command: ["pm2-docker", "process.yml", "--only", "APP"]
  worker:
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    command: ["pm2-docker", "process.yml", "--only", "WORKER"]
